//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMisOfertas : DbContext
    {
        public EntitiesMisOfertas()
            : base("name=EntitiesMisOfertas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATGORIAPRODUCTO> CATGORIAPRODUCTOes { get; set; }
        public DbSet<COMUNA> COMUNAs { get; set; }
        public DbSet<EMPRESA> EMPRESAs { get; set; }
        public DbSet<MARCA> MARCAs { get; set; }
        public DbSet<OFERTA> OFERTAs { get; set; }
        public DbSet<PRIORIDAD> PRIORIDADs { get; set; }
        public DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public DbSet<REGION> REGIONs { get; set; }
        public DbSet<RUBROPRODUCTO> RUBROPRODUCTOes { get; set; }
        public DbSet<TICKETDESCUENTO> TICKETDESCUENTOes { get; set; }
        public DbSet<TIENDA> TIENDAs { get; set; }
        public DbSet<TIENDA_PRODUCO> TIENDA_PRODUCO { get; set; }
        public DbSet<TIPOUSUARIO> TIPOUSUARIOs { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
        public DbSet<VALORACION> VALORACIONs { get; set; }
    }
}
