//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesOfertas : DbContext
    {
        public EntitiesOfertas()
            : base("name=EntitiesOfertas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATGORIAPRODUCTO> CATGORIAPRODUCTO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRIORIDAD> PRIORIDAD { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RUBROPRODUCTO> RUBROPRODUCTO { get; set; }
        public DbSet<TICKETDESCUENTO> TICKETDESCUENTO { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<TIENDA_PRODUCO> TIENDA_PRODUCO { get; set; }
        public DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
    }
}
