//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETDESCUENTO
    {
        public TICKETDESCUENTO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_TICKET { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public decimal DESCUENTO_OTORGADO { get; set; }
        public byte[] CODIGOBARRA { get; set; }
        public decimal TOPE { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
