//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDA
    {
        public decimal ID_TIENDA { get; set; }
        public string NOMBRE_TIENDA { get; set; }
        public string DIRECCION_TIENDA { get; set; }
        public string TELEFONO_TIENDA { get; set; }
        public decimal COMUNA_ID_COMUNA { get; set; }
        public decimal EMPRESA_ID_EMPRESA { get; set; }
    }
}
