//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APEPA_USUARIO { get; set; }
        public string APEMA_USUARIO { get; set; }
        public string CORREO_USUARIO { get; set; }
        public string RUT_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public string TELEFONO_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public Nullable<decimal> PUNTOS_USUARIO { get; set; }
        public Nullable<decimal> TIPOUSUARIO_ID_TIPOUSUARIO { get; set; }
        public decimal COMUNA_ID_COMUNA { get; set; }
        public Nullable<decimal> PRIORIDAD_ID_VISITA { get; set; }
        public Nullable<decimal> TIENDA_ID_TIENDA { get; set; }
        public Nullable<decimal> TICKETDESCUENTO_ID_TICKET { get; set; }
    }
}
