//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.VALORACION = new HashSet<VALORACION>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APEPA_USUARIO { get; set; }
        public string APEMA_USUARIO { get; set; }
        public string CORREO_USUARIO { get; set; }
        public string RUT_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public string TELEFONO_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public decimal PUNTOS_USUARIO { get; set; }
        public decimal TIPOUSUARIO_ID_TIPOUSUARIO { get; set; }
        public decimal COMUNA_ID_COMUNA { get; set; }
        public decimal PRIORIDAD_ID_VISITA { get; set; }
        public decimal TIENDA_ID_TIENDA { get; set; }
        public decimal TICKETDESCUENTO_ID_TICKET { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual PRIORIDAD PRIORIDAD { get; set; }
        public virtual TICKETDESCUENTO TICKETDESCUENTO { get; set; }
        public virtual TIENDA TIENDA { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
    }
}
